// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkllfukfzewnzlixincp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbGxmdWtmemV3bnpsaXhpbmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk1NjUsImV4cCI6MjA2NTU4NTU2NX0.Kiy1bP8gJ9RYBZqSviCeX45_9uUZcHhurTjr_tjkw60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);